[package]
name = "rust_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { path = "deps/gdextension/godot" }
dungeon_stranding = { path = "deps/dungeon_stranding" }
owning_ref = "*"
num-derive = "*"
num-traits = "*"
