[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-arg=-sSIDE_MODULE=2",
    #"-Clink-arg=-pthread",
    "-Clink-arg=-sUSE_PTHREADS=1",
    "-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals",
    "-Zlink-native-libraries=no",
]
